services:
  api:
    build: .
    container_name: fastapi-ocr-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: Docker.frontend
    ports:
      - "80:80"
